
'Name'
'Type'
'Rarity'
'Base ATK'
'EM'
'CRIT RATE'
'CRIT DMG'
'ER'
'Elemental DMG'
'Physical DMG'
'ATK%'
'DEF%'
'HP%'
'Healing Bonus'



'All DMG'
'Normal Attack DMG'
'Charged Attack DMG'
'Plunging Attack DMG'
'Elemental Skill DMG'
'Elemental Burst DMG'
'Flat ATK'
'Additive Base DMG Normal Attack'
'Additive Base DMG Charged Attacks'
'Additive Base DMG Charged Attack'
'Additive Base DMG Elemental Skill'
'Bond of Life% (BoL)'